apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 2121

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.121
  selector:
    app: ftps
  ports:
  - port      : 21
    name      : http-ftps
    protocol  : TCP
    targetPort: 21
  - port      : 2121
    name      : pwd-ftps
    protocol  : TCP
    targetPort: 2121