apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: custom-ip-pool
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.150

# 192.168.99.121 - ftps
# 192.168.99.100 - nginx
# 192.168.99.145 - phpMyAdmin
# 192.168.99.150 - WordPress

