apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadm
        image: phpmyadm_img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.145
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: http-phpmyadm
    protocol: TCP
    targetPort: 5000